{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.20.1-v2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.1-v2.toml",
          "url": "sharedcatalogs-1.20.1-v2.toml",
          "size": 3623,
          "sha512": "ddecb764e778118f0c2dab208bab80d47367f24b9fe1fb75b9361fbbdc2e94acca37be74808ac55f480a3063181172a2ff97067a20dfd2c5e4a46761607a51d1",
          "sha256": "6c5017b94d2a7d39d429da15759cc73455984a973fe1f52e9ae267c8c8771b3b",
          "sha1": "6d226693bba86898b1d53cfbc5469f017af8d59c",
          "md5": "9ce585c4e09dac8e653becf96cfde703"
        }
      ]
    }
  ]
}
