{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.20.1-v2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.1-v2.toml",
          "url": "sharedcatalogs-1.20.1-v2.toml",
          "size": 3512,
          "sha512": "77dc6d9d2db90a8509efe513d63690a77afea3fe2761757328aa8cbea7efc04646ba320c20b6f453ac61a60aa7017965bb98b8ceb1db2381cf56ef05cd5e29d2",
          "sha256": "8ebbcd91d6532c561935e1808a6e31ebd215ed2edd996896c74f7cf57d27a8cf",
          "sha1": "f0f6ab5d37ad51725cb59c56e1441dca465f495f",
          "md5": "918902bdfa9e14533cfab626d2a4b009"
        }
      ]
    }
  ]
}
