{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.21.1-v9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.1-v9.toml",
          "url": "sharedcatalogs-1.21.1-v9.toml",
          "size": 4313,
          "sha512": "913f22598915474dac1fc520a6eea0a42f215325b850f3e23f49390def6bec8146535394f23529099de29f165062768cfd4d12644c3f8961953e3d56ee9d6b02",
          "sha256": "987275141c2a1687ec3363e9a415b342460e15d6525dede73d7a9709cb427b96",
          "sha1": "ec6b69459dc952e75b59f0a52e888b8c3880ae45",
          "md5": "dcfa9103f965800f04dbb6ac6d425ffb"
        }
      ]
    }
  ]
}
