{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.20.1-v5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.1-v5.toml",
          "url": "sharedcatalogs-1.20.1-v5.toml",
          "size": 3779,
          "sha512": "29c92ecd2217e6fb5bf42174df1be22b946c939504e1ce29f5944d9cec239943bea79915bc1093365a7917304e5ac8ae6320ed8ded52e4d69fe29b15e0f643b9",
          "sha256": "3ac7f75153abba3c4052bc998fd626b5c1c8327cd19b9f6407f7d789fea06e0a",
          "sha1": "3f670f4ffc80c39c924e49746a4ce0e46477d79b",
          "md5": "62105e0f2d1a83e7609fb9b114d7968f"
        }
      ]
    }
  ]
}
