{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.20.1-v5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.1-v5.toml",
          "url": "sharedcatalogs-1.20.1-v5.toml",
          "size": 3773,
          "sha512": "919e13cba80ebe57be30ee236d71d14f485beb817e7085de3a63b56f77d3435139dc5a984b2e37a33290388d0f1d55c2015d041b6e4b82676202705b70189db4",
          "sha256": "1a441821913da9dbee99d6d82279a258de3b813ec6854f9d2aacb37f953c8377",
          "sha1": "e3c29462bf061b8d4cff33db30be06daed44523a",
          "md5": "434c887d945e1139a2ad1ab5c9a003c6"
        }
      ]
    }
  ]
}
