{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.20.1-v5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.1-v5.toml",
          "url": "sharedcatalogs-1.20.1-v5.toml",
          "size": 3773,
          "sha512": "532a329dfa9638134ab17de4a417802d6e2e51e49aa5ca8d321b4b5457401dbaf9d5fffa4b7cc86a962ea950bf933047ed2960e1e1691756d7fbba12eac3d6a9",
          "sha256": "ce660d49180322cb1838718ae7440f9f79b8519a5b8ad328e3d1ea50f0cc4225",
          "sha1": "6504989066f50228b08a93eb0c5550c2a8d6ec82",
          "md5": "899347342661d3c03cde14c5dd08854b"
        }
      ]
    }
  ]
}
