{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord.hytale-devkit",
    "module": "hytale-devkit-runtime",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hytale-devkit-runtime-1.0.jar",
          "url": "hytale-devkit-runtime-1.0.jar",
          "size": 11947,
          "sha512": "725f2ddf5ea01e33b999c4f91786e432e201c18aed86271c19698cbf37ec1d180f4ddc8c62de3e567d5d909da1d6ccb5b8df5e84329f15547cf8a893e7504e84",
          "sha256": "a0627c786ff37f9329ccfec3d88bcc80608595f518a0e8ce1ed706ca471aad63",
          "sha1": "8717ecbfb87bcf74c881538b7f5f88c246f442b9",
          "md5": "4d8f6da312aeaa583143163635b12d77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hytale-devkit-runtime-1.0.jar",
          "url": "hytale-devkit-runtime-1.0.jar",
          "size": 11947,
          "sha512": "725f2ddf5ea01e33b999c4f91786e432e201c18aed86271c19698cbf37ec1d180f4ddc8c62de3e567d5d909da1d6ccb5b8df5e84329f15547cf8a893e7504e84",
          "sha256": "a0627c786ff37f9329ccfec3d88bcc80608595f518a0e8ce1ed706ca471aad63",
          "sha1": "8717ecbfb87bcf74c881538b7f5f88c246f442b9",
          "md5": "4d8f6da312aeaa583143163635b12d77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hytale-devkit-runtime-1.0-sources.jar",
          "url": "hytale-devkit-runtime-1.0-sources.jar",
          "size": 6901,
          "sha512": "646fd35f83978660df843d6ed2db226a5e0200d2bc5a4ee0735eefc02065264c39ec2788011f9a15f5e3fdb00a9ac35054d3331e4c30dc85547fbb2f026fe8a6",
          "sha256": "67e3c9eae73fa222fb9a5cbd1c095db4ac343e859d6f9c393b85bb87aad8a9ec",
          "sha1": "7b2aa9e375bbf31beb0e641955f7bd59446e8a46",
          "md5": "fb5396948468a2698e76c4269144696b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hytale-devkit-runtime-1.0-javadoc.jar",
          "url": "hytale-devkit-runtime-1.0-javadoc.jar",
          "size": 4181519,
          "sha512": "14f2bd79c2a839d60a4773d04e926a8a90c99be24dd60f4595760e554e6d9f8ae6f2556d95f4bd1478217c3a5d4459f8dc736eeb1526b7b214dbb9aa004c6812",
          "sha256": "ba632ea8e11e33938ce28f4462778f0c64e33d725d87e3d8a72dc88500c5f5e5",
          "sha1": "60178142e82a1d8e8a7627f6663381dcb08eafa6",
          "md5": "42180f66f8c26d6a3cd323e3d14f6466"
        }
      ]
    }
  ]
}
