{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord.hytale-devkit",
    "module": "hytale-devkit-runtime",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hytale-devkit-runtime-1.0.jar",
          "url": "hytale-devkit-runtime-1.0.jar",
          "size": 12039,
          "sha512": "d47cc9a1aabbe4654549bdcc4263bf41192f73cf925dbaedae5657b630e2654349fb02a3ecac9741644d398d80c42bdf8521d1b8ebe92c54d8c829fd90ae725b",
          "sha256": "857774da5eb8209dc8111e441f1e3b8953f2e42b33fe0fc168b5d71d0d582f38",
          "sha1": "903b6ff8f86ea06a7bb3737ab4d596c128b3a72b",
          "md5": "2abe38eee856b87df516baf806c05888"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hytale-devkit-runtime-1.0.jar",
          "url": "hytale-devkit-runtime-1.0.jar",
          "size": 12039,
          "sha512": "d47cc9a1aabbe4654549bdcc4263bf41192f73cf925dbaedae5657b630e2654349fb02a3ecac9741644d398d80c42bdf8521d1b8ebe92c54d8c829fd90ae725b",
          "sha256": "857774da5eb8209dc8111e441f1e3b8953f2e42b33fe0fc168b5d71d0d582f38",
          "sha1": "903b6ff8f86ea06a7bb3737ab4d596c128b3a72b",
          "md5": "2abe38eee856b87df516baf806c05888"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hytale-devkit-runtime-1.0-sources.jar",
          "url": "hytale-devkit-runtime-1.0-sources.jar",
          "size": 6968,
          "sha512": "fdd0d6c9aa5ef81f4d6c284f23de0c2d7a5cbaa8de844f1f536e6429df97697e2ace0b2c52cabd59e550015c06abe8f04c0036f556f7f43a44a04f75e412c31b",
          "sha256": "a98ba10c1da690321a98a6d0b16413d6a99be92057c26d71f3802d9cd2639e72",
          "sha1": "529e6f5536e4382b5401c395a9aa297e2ebf5af1",
          "md5": "b06afd5d3e9ca784ab538e2cffd84e9f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hytale-devkit-runtime-1.0-javadoc.jar",
          "url": "hytale-devkit-runtime-1.0-javadoc.jar",
          "size": 4182117,
          "sha512": "91cfffbdd93017c34d5893c38fbf194dd54b76c230795dbb46247d21465a87baf57020d3781a14d43440c9e2c911b8ea1425ea5b72b29141205f88b4c59259ab",
          "sha256": "936e8cd29a375458a8058a70971241aa66e61b653f2a76a393e7f69701d4cfcc",
          "sha1": "d44613453080f147650e6dc23519afee7c41d58e",
          "md5": "d1710ecb7b1677af5df47fa03945bb58"
        }
      ]
    }
  ]
}
