{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "hytale-devkit",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "hytale-devkit-1.0.jar",
          "url": "hytale-devkit-1.0.jar",
          "size": 109217,
          "sha512": "badbe5cde853a0f8d7a3d85a1906eaa2f3318e34c56ec27d31e4025b5b9b4c6d0c78f96e263f3be0cf30a2e87b2bd5867add2d567eb73dd483ebac111b28ecfb",
          "sha256": "cbfb88950a2578ae801878a30544bf3ec6acb0f79d199f0fc701c501fb55156b",
          "sha1": "07f5f3d0f7a8d7b44fcac3aa41fbca4b9cfdab58",
          "md5": "813b83ba0d61228a99ef83cf4dd0b3e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "hytale-devkit-1.0.jar",
          "url": "hytale-devkit-1.0.jar",
          "size": 109217,
          "sha512": "badbe5cde853a0f8d7a3d85a1906eaa2f3318e34c56ec27d31e4025b5b9b4c6d0c78f96e263f3be0cf30a2e87b2bd5867add2d567eb73dd483ebac111b28ecfb",
          "sha256": "cbfb88950a2578ae801878a30544bf3ec6acb0f79d199f0fc701c501fb55156b",
          "sha1": "07f5f3d0f7a8d7b44fcac3aa41fbca4b9cfdab58",
          "md5": "813b83ba0d61228a99ef83cf4dd0b3e5"
        }
      ]
    }
  ]
}
