{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "hytale-devkit",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "hytale-devkit-1.0.jar",
          "url": "hytale-devkit-1.0.jar",
          "size": 109145,
          "sha512": "c59e8a324b24ad25c9c92de4d06d804573530b2b3094254d9e28dc5fe2ab22fe7b5c64afd8dbcee1fa60e7c38f6cf95493d9338d97ecd81c44928dddfabfd4fd",
          "sha256": "316f3179df4cd2ba6d2dfce88b30e4cb534ba79553e532ff04a3040fa5cb020a",
          "sha1": "aa3b3641832aa9ee2f13daad762db04a00d7e82a",
          "md5": "441bcd0c2f10c2f638df22bdbb2781e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "hytale-devkit-1.0.jar",
          "url": "hytale-devkit-1.0.jar",
          "size": 109145,
          "sha512": "c59e8a324b24ad25c9c92de4d06d804573530b2b3094254d9e28dc5fe2ab22fe7b5c64afd8dbcee1fa60e7c38f6cf95493d9338d97ecd81c44928dddfabfd4fd",
          "sha256": "316f3179df4cd2ba6d2dfce88b30e4cb534ba79553e532ff04a3040fa5cb020a",
          "sha1": "aa3b3641832aa9ee2f13daad762db04a00d7e82a",
          "md5": "441bcd0c2f10c2f638df22bdbb2781e7"
        }
      ]
    }
  ]
}
