{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.21.1-v7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.1-v7.toml",
          "url": "sharedcatalogs-1.21.1-v7.toml",
          "size": 4265,
          "sha512": "73d503257a55b303e16e01d81ff536c4284805ad0c4a744f50881bef11c4ba4700ccec959284cb8e0c24ab5fb682d8c96fe14a251822723955cb6e8b75ed1a42",
          "sha256": "22cfe421e39e70763105a55e51c44946588e9d2021f8821d9a583a294ee51255",
          "sha1": "23c62a81bd446267aa2fad53d38ba772c331adb3",
          "md5": "8356bf2a11f14bd4f95f81db3f3aecf4"
        }
      ]
    }
  ]
}
