{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.21-v2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21-v2.toml",
          "url": "sharedcatalogs-1.21-v2.toml",
          "size": 4201,
          "sha512": "feca914f25085d7c1a177da3da511c2ebe26e8a466a1e0baa44a477f3d503b971d06d33f61332dc2728af79456f170aa7664102a3b929a3ef61bc2fe86f7eb98",
          "sha256": "a036061632173957a6867d8f7ac7787550144131d4ad00098b1974fa2b73f39d",
          "sha1": "50ea9b2a3069b8b230a9b9daa5f3f35ab7c05ff6",
          "md5": "96fe151623533d89274cf4b4cb66c17e"
        }
      ]
    }
  ]
}
