{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.21-v2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21-v2.toml",
          "url": "sharedcatalogs-1.21-v2.toml",
          "size": 4211,
          "sha512": "9459423d0d6a992c1f2f0906df3a781fd8e8982ecd49a14dd268424a69f5d1b8f07ff11080c9b730b9b0dc7c16b36315eb0cfff3a972859fbb979dfced9b3768",
          "sha256": "a79c48348c33b3a22a866618554cce7878d6231e5d9dc01b42fea5363fe71344",
          "sha1": "c0254ff4f0c111728400bae05ab36c06a7d45595",
          "md5": "69c05112be291bee1b56d0e416b2ac29"
        }
      ]
    }
  ]
}
