{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.21.1-v1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.1-v1.toml",
          "url": "sharedcatalogs-1.21.1-v1.toml",
          "size": 3604,
          "sha512": "69dd68a0316e0a48bcac3e42f5e79937d01be6fe577a5308d81c68ab48eaabf07199e8d7290051cd7f65147d7e48fd3c558a2ae12753879bdcc9c4af4648b5c3",
          "sha256": "9ac28f94f2f98c6e540d9dcc2ad4bfa67b54bd2aa692209103c0fcc4fbf7c4f0",
          "sha1": "2176ac2ca89ad1976670cb1647f79bdf80dc711f",
          "md5": "a4620bbc4f91d42ea34066186711dac0"
        }
      ]
    }
  ]
}
