{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.21.1-v1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.1-v1.toml",
          "url": "sharedcatalogs-1.21.1-v1.toml",
          "size": 3611,
          "sha512": "d4ef2eed817da79d654e743c884bb557d2f85a2afaf2f3b56be3991462c7a6228547843dacbac8ba5344dbcbf52ab1f4d6106edee6a420857696e403d632d659",
          "sha256": "8290d89859771e821bd3a38ed3900a93120d4b9ae9dbcfb77d288fcd50e1a069",
          "sha1": "eea15f54be018a3e100e21ca0ffb73662587dbf8",
          "md5": "544a6b61f06c60919c806d75b0947947"
        }
      ]
    }
  ]
}
