{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.21.1-v1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.1-v1.toml",
          "url": "sharedcatalogs-1.21.1-v1.toml",
          "size": 3623,
          "sha512": "d4581fa815902aee92a6587494b11c15c708ce7bf5a828b42db51ad1edae655450129186c9c33abc8fdd38b944af39680952c4c6fda5e61c9a6c321ec560f199",
          "sha256": "37fa9ae964e528258052506131a8ada146ee20e6ff245598904a1d448b01c7ce",
          "sha1": "47be6eec42cd88c0cd784ae76ff87330eb1f83f9",
          "md5": "67ddb6d3537d06c978531de7e7169fae"
        }
      ]
    }
  ]
}
