[versions]
java = "21"
minecraft = "1.21.1"
fabricapi-min = "0.102.0"
fabricapi-version = "0.105.0+1.21.1"
fabricloader-min = "0.16.1"
fabricloader-version = "0.16.5"
minecraftforge-min = "52.0.0"
minecraftforge-version = "52.0.15"
neoforge-min = "21.1.21"
neoforge-version = "21.1.64"
neoforgedatapackextensions = "21.1.0"
parchment-minecraft = "1.21"
parchment-version = "2024.07.28"
mixinextras-version = "0.4.1"
architectury = "13.0.2"
data = "48"
modmenu = "11.0.2"
jei = "19.16.4.170"
rei = "16.0.762"
emi = "1.1.13+1.21.1"
curios = "9.0.9+1.21"
trinkets = "3.10.0"

[libraries]
architectury-fabric = {group = "dev.architectury", name = "architectury-fabric", version.ref = "architectury" }
architectury-neoforge = {group = "dev.architectury", name = "architectury-neoforge", version.ref = "architectury" }
curios-neoforge = {group = "top.theillusivec4.curios", name = "curios-neoforge", version.ref = "curios" }
emi-common = {group = "dev.emi", name = "emi-xplat-mojmap", version.ref = "emi" }
emi-fabric = {group = "dev.emi", name = "emi-fabric", version.ref = "emi" }
emi-neoforge = {group = "dev.emi", name = "emi-neoforge", version.ref = "emi" }
fabricapi-fabric = {group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabricapi-version" }
fabricloader-fabric = {group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricloader-version" }
jei-fabric = {group = "mezz.jei", name = "jei-1.21.1-fabric", version.ref = "jei" }
jei-neoforge = {group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
jeiapi-common = {group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }
jeiapi-fabric = {group = "mezz.jei", name = "jei-1.21.1-fabric-api", version.ref = "jei" }
jeiapi-neoforge = {group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jei" }
jeilibs-common = {group = "mezz.jei", name = "jei-1.21.1-lib", version.ref = "jei" }
minecraftforge-forge = {group = "net.minecraftforge", name = "forge", version.ref = "minecraftforge-version" }
mixinextras-common = {group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras-version" }
mixinextras-forge = {group = "io.github.llamalad7", name = "mixinextras-forge", version.ref = "mixinextras-version" }
modmenu-fabric = {group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }
neoforge-neoforge = {group = "net.neoforged", name = "neoforge", version.ref = "neoforge-version" }
neoforgedatapackextensions-common = {group = "fuzs.neoforgedatapackextensions", name = "neoforgedatapackextensions-common", version.ref = "neoforgedatapackextensions" }
neoforgedatapackextensions-fabric = {group = "fuzs.neoforgedatapackextensions", name = "neoforgedatapackextensions-fabric", version.ref = "neoforgedatapackextensions" }
neoforgedatapackextensions-neoforge = {group = "fuzs.neoforgedatapackextensions", name = "neoforgedatapackextensions-neoforge", version.ref = "neoforgedatapackextensions" }
rei-fabric = {group = "me.shedaniel", name = "RoughlyEnoughItems-fabric", version.ref = "rei" }
rei-neoforge = {group = "me.shedaniel", name = "RoughlyEnoughItems-neoforge", version.ref = "rei" }
reiapi-common = {group = "me.shedaniel", name = "RoughlyEnoughItems-api", version.ref = "rei" }
reiapi-fabric = {group = "me.shedaniel", name = "RoughlyEnoughItems-api-fabric", version.ref = "rei" }
reiapi-neoforge = {group = "me.shedaniel", name = "RoughlyEnoughItems-api-neoforge", version.ref = "rei" }
reidefaultplugin-common = {group = "me.shedaniel", name = "RoughlyEnoughItems-default-plugin", version.ref = "rei" }
reidefaultplugin-fabric = {group = "me.shedaniel", name = "RoughlyEnoughItems-default-plugin-fabric", version.ref = "rei" }
reidefaultplugin-neoforge = {group = "me.shedaniel", name = "RoughlyEnoughItems-default-plugin-neoforge", version.ref = "rei" }
trinkets-fabric = {group = "dev.emi", name = "trinkets", version.ref = "trinkets" }