{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "1.21-v3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21-v3.toml",
          "url": "sharedcatalogs-1.21-v3.toml",
          "size": 4215,
          "sha512": "483a724d119aaaf65c6462b44a65ea7e9c485c2d8cc557b227b0a73432c4d6619201ddc01c610e5ac6fbe8776734570389f7d5eef9c9d2237444080cdec06b89",
          "sha256": "8ca480cd34088671a0de68475096e119bb74578eb3d358e10d8f6f1c107f00e8",
          "sha1": "61484bd829d7cd3267d73620d04c84b782280e7b",
          "md5": "70c3ab1facc21a897a19e140873a87fc"
        }
      ]
    }
  ]
}
