{
  "formatVersion": "1.1",
  "component": {
    "group": "net.ixdarklord",
    "module": "sharedcatalogs",
    "version": "26.1.2-v2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-26.1.2-v2.toml",
          "url": "sharedcatalogs-26.1.2-v2.toml",
          "size": 4490,
          "sha512": "2b247e8feffe532726ae090d6a58aa981fbb34e4cce37c11c61dc9a6741b559b9d6a75003e467a8879b54d29b5ced967af82d9b8c2b4d634c3c6ca3d27a6e9a6",
          "sha256": "ab213b817c1303c0b4745416d20432bf390d1a6c0eb3d957416b6d2aec4160b6",
          "sha1": "9b933ba138859cff3d30a3e97f6a72b3b8a56aae",
          "md5": "cb0dbf81b2a873b53d49bda4bce931c1"
        }
      ]
    }
  ]
}
